language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: false

cache:
  directories:
    - node_modules

env:
  - DIALECT=mysql
  - DIALECT=postgres
  - DIALECT=postgres-native
  - DIALECT=sqlite
  - DIALECT=mariadb

addons:
  postgresql: "9.4"

before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"
  - "psql sequelize_test -c 'create extension postgis;' -U postgres"

script:
  - "npm test"

branches:
  only:
  - master
  - v3

